### ISSUE TITLE
run of mac os ???

### ISSUE THREAD

**Issue by pullghjunkkk** [nicholasaleks/Damn-Vulnerable-Drone#17]
paulchikkkk@bb6699 Damn-Vulnerable-Drone %  sudo ./start.sh --no-wifi
[+] Running System clean up...
[+] Stopping Docker Compose services...
WARN[0000] The "XDG_RUNTIME_DIR" variable is not set. Defaulting to a blank string. 
WARN[0000] /Users/paulchikkkk/Damn-Vulnerable-Drone/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
./start.sh: line 132: iw: command not found
sudo: modprobe: command not found
sudo: service: command not found
sudo: service: command not found
[+] System Ready...
Starting simulation assuming drone network connectivity access...
[+] Starting Docker Compose...
time="2024-10-15T11:21:54+08:00" level=warning msg="The \"XDG_RUNTIME_DIR\" variable is not set. Defaulting to a blank string."
time="2024-10-15T11:21:54+08:00" level=warning msg="/Users/paulchikkkk/Damn-Vulnerable-Drone/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
#0 building with "desktop-linux" instance using docker driver

#1 [simulator internal] load build definition from Dockerfile
#1 transferring dockerfile: 3.84kB done
#1 DONE 0.1s

#2 [flight-controller internal] load build definition from Dockerfile
#2 transferring dockerfile: 1.96kB done
#2 DONE 0.0s

#3 [qgc internal] load build definition from Dockerfile
#3 transferring dockerfile: 2.90kB done
#3 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
#3 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 32)
#3 WARN: InvalidDefaultArgInFrom: Default value for ARG ${BASEIMAGE}:${BASETAG} results in empty or invalid base image name (line 5)
#3 WARN: InvalidDefaultArgInFrom: Default value for ARG ${BASEIMAGE}:${BASETAG} results in empty or invalid base image name (line 32)
#3 DONE 0.1s

#4 [qgc internal] load metadata for docker.io/library/ubuntu:22.04
2024/10/15 11:21:56 must use ASL logging (which requires CGO) if running as root
#4 ...

#5 [simulator internal] load metadata for docker.io/library/ubuntu:20.04
#5 ERROR: error getting credentials - err: exit status 1, out: ``
2024/10/15 11:21:56 must use ASL logging (which requires CGO) if running as root

#4 [qgc internal] load metadata for docker.io/library/ubuntu:22.04
#4 ERROR: error getting credentials - err: exit status 1, out: ``
------
 > [simulator internal] load metadata for docker.io/library/ubuntu:20.04:
------
------
 > [qgc internal] load metadata for docker.io/library/ubuntu:22.04:
------
failed to solve: ubuntu:20.04: failed to resolve source metadata for docker.io/library/ubuntu:20.04: error getting credentials - err: exit status 1, out: ``

.--------------------------------------------------------------------------------.
         .###+             .#####               ####+             .####          
          #######.######-+#+####                .###+##.######+.######-          
           -#######    .#+#####                  .#####+#    .#+#####      
           +#.######.+.#####. .#   .+#######+.  +#  +#####--######+-#      
          +#.     .#####+      +####-      .####+-     --#####      +#     
          #+     +###+-#++    ###           +##.##-    ##+-####-     #+    
          ##   +######+###.+-##  .++.      ..##  -##---##+#######-   #-    
          +##-############-.##. -######+      -#  .##.+############-##     
           -######-     .##+#..  ##########.    -#-+#-#+      #######      
            ##############+##.#    ##########   .-+-#-##############.      
                           +#++       -###### ....###                      
                            ## .+         .  ..-#+##-                      
                            ## ####+.     .-+#######+                      
                           -#. .######.+#.-#######-##                      
                            ##        .###     .+.-##                      
                             ###++.   +#-#    .+###.                       
                            .######-        .#######                       
         -####+            #########.-  - . .########-           .#####    
           +###+##-######+-##########.#  + --.##########.######-#######     
            #####+#  .  #+###############################    +#+####+      
           #+ +#####.+.######+ - ##          +#. ..#######-.######. #-     
          ##      -#####+     .#..#.         ## #+     --#####      -#.    
          #-   -#####++#++     ## #+         #- #-     ###++####+.   #+    
          ## +#######++##-     ##            .  ##     ###+#######+-.#.    
           #######--###-     -##                -##     .+###.########     
          ######-         .####                  .###+          #######    
          ++. +#############-                       +#############..-+-    
                   .---.                                .----. 

.--------------------------------------------------------------------------------.
|░█▀▄░█▀█░█▄█░█▀█░░░█░█░█░█░█░░░█▀█░█▀▀░█▀▄░█▀█░█▀▄░█░░░█▀▀░░░█▀▄░█▀▄░█▀█░█▀█░█▀▀|
|░█░█░█▀█░█░█░█░█░░░▀▄▀░█░█░█░░░█░█░█▀▀░█▀▄░█▀█░█▀▄░█░░░█▀▀░░░█░█░█▀▄░█░█░█░█░█▀▀|
|░▀▀░░▀░▀░▀░▀░▀░▀░░░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀░░▀▀▀░▀▀▀░░░▀▀░░▀░▀░▀▀▀░▀░▀░▀▀▀|
'--------------------------------------------------------------------------------'                                                                                                                   
    
------------------------------------------------------
[+] Build Complete.
[+] Version: 1.0.0
------------------------------------------------------
[+] Damn Vulnerable Drone Lab Environment is running...
[+] Log file: dvd.log
[+] Simulator: http://localhost:8000
------------------------------------------------------
time="2024-10-15T11:21:56+08:00" level=warning msg="The \"XDG_RUNTIME_DIR\" variable is not set. Defaulting to a blank string."
time="2024-10-15T11:21:56+08:00" level=warning msg="/Users/paulchikkkk/Damn-Vulnerable-Drone/docker-compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"

**Comment by unfixa1** [comment]
Set XDG_RUNTIME_DIR:
You can set this environment variable in the terminal, for example:

export XDG_RUNTIME_DIR=/tmp

In addition, you can use [Servbay](https://servbay.com) to check your development environment, which is more useful than Docker on Mac and can ensure that there is no compatibility conflict in the environment

**Comment by nicholasaleks** [comment]
Running Damn Vulnerable Drone on MacOS is not supported. Feel free to submit a PR if you believe your suggestions may fix it.
