### ISSUE TITLE
The key is incorrect

### ISSUE THREAD

**Issue by lapsleep** [nicholasaleks/Damn-Vulnerable-Drone#18]
> [simulator  5/28] RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -:
0.323 Warning: apt-key output should not be parsed (stdout is not a terminal)
0.342 gpg: no valid OpenPGP data found.
------
failed to solve: process "/bin/sh -c curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -" did not complete successfully: exit code: 2

Can you help me

**Comment by lapsleep** [comment]
![image](https://github.com/user-attachments/assets/39979344-7d4a-4f68-8166-198cc53b6e31)
When I use compose it is so

**Comment by pljoel** [comment]
@lapsleep I'm not having this issue. The ROS PGP file seems valid until mid 2025. 
What OS are you working on; what's the output from `cat /etc/*release*`?

**Comment by ch0en3** [comment]
try to check your proxy. I have same problem but i solve now.This problem is China's network problems .

**Comment by nicholasaleks** [comment]
Perhaps also try restarting Docker

**Comment by nicholasaleks** [comment]
Closing issue as it does not seem related to DVD
